#!/bin/bash -e

declare -rx BENCHERL_CMD="${0##*/}"

#
# source the measure script so we can use its environment to know what to do
#
. "$(dirname "$0")/script/measure.sh"

declare -i _be_xc=0

if $BENCHERL_PLOT || $BENCHERL_CHECK_SANITY
then
    for _be_bench in "${_be_benchmarks[@]}"
    do
        _be_results="$BENCHERL_RESULTS/$_be_bench"
        _be_odir="$_be_results/output"

        if $BENCHERL_CHECK_SANITY
        then
            echo "*** Checking '$_be_bench' output ..."

            if ! check_benchmark_output "$_be_odir"
            then
                echo "!!! Benchmark '$_be_bench' FAILED sanity check!" >&2
                let '_be_xc += 1'
                continue
            fi
        fi
        $BENCHERL_PLOT || continue

        _be_mdir="$_be_results/measurements"
        _be_gdir="$_be_results/graphs"

        echo "*** Plotting '$_be_bench' results ..."

        "$BENCHERL_SCRIPTS/plot.sh" "$_be_bench" "$_be_mdir" "$_be_gdir"
    done
fi

exit $_be_xc
